const products = [
  { title: "The Great Gatsby", author: "F. Scott Fitzgerald", price: 10.99, year: 1925 },
  { title: "To Kill a Mockingbird", author: "Harper Lee", price: 12.99, year: 1960 },
  { title: "1984", author: "George Orwell", price: 9.99, year: 1949 },
  { title: "Pride and Prejudice", author: "Jane Austen", price: 8.99, year: 1813 },
  { title: "Moby-Dick", author: "Herman Melville", price: 11.99, year: 1851 },
  { title: "The Catcher in the Rye", author: "J.D. Salinger", price: 10.49, year: 1951 },
  { title: "Brave New World", author: "Aldous Huxley", price: 13.99, year: 1932 },
  { title: "The Hobbit", author: "J.R.R. Tolkien", price: 14.99, year: 1937 },
  { title: "Fahrenheit 451", author: "Ray Bradbury", price: 9.49, year: 1953 },
  { title: "Jane Eyre", author: "Charlotte Brontë", price: 11.49, year: 1847 },
  { title: "The Alchemist", author: "Paulo Coelho", price: 15.99, year: 1988 },
  { title: "Crime and Punishment", author: "Fyodor Dostoevsky", price: 12.49, year: 1866 },
  { title: "The Odyssey", author: "Homer", price: 13.49, year: -700 },
  { title: "Animal Farm", author: "George Orwell", price: 8.49, year: 1945 },
  { title: "War and Peace", author: "Leo Tolstoy", price: 18.99, year: 1869 },
  { title: "The Kite Runner", author: "Khaled Hosseini", price: 14.49, year: 2003 },
  { title: "The Book Thief", author: "Markus Zusak", price: 13.99, year: 2005 },
  { title: "Dune", author: "Frank Herbert", price: 16.99, year: 1965 },
  { title: "The Lord of the Rings", author: "J.R.R. Tolkien", price: 24.99, year: 1954 },
  { title: "Harry Potter and the Sorcerer's Stone", author: "J.K. Rowling", price: 12.99, year: 1997 },
  { title: "The Chronicles of Narnia", author: "C.S. Lewis", price: 19.99, year: 1950 },
  { title: "Frankenstein", author: "Mary Shelley", price: 9.99, year: 1818 },
  { title: "Dracula", author: "Bram Stoker", price: 10.99, year: 1897 },
  { title: "The Shining", author: "Stephen King", price: 15.49, year: 1977 },
  { title: "The Hunger Games", author: "Suzanne Collins", price: 11.99, year: 2008 },
  { title: "The Fault in Our Stars", author: "John Green", price: 10.49, year: 2012 },
  { title: "A Tale of Two Cities", author: "Charles Dickens", price: 9.49, year: 1859 },
  { title: "Les Misérables", author: "Victor Hugo", price: 17.99, year: 1862 },
  { title: "The Da Vinci Code", author: "Dan Brown", price: 13.49, year: 2003 },
  { title: "The Little Prince", author: "Antoine de Saint-Exupéry", price: 8.99, year: 1943 }
];

module.exports = products;