const products = [
  { name: "Laptop", price: 899.99, quantity: 10, warehouse: "A" },
  { name: "Mouse", price: 19.99, quantity: 150, warehouse: "B" },
  { name: "Keyboard", price: 49.99, quantity: 85, warehouse: "A" },
  { name: "Monitor", price: 199.99, quantity: 40, warehouse: "C" },
  { name: "Printer", price: 129.99, quantity: 25, warehouse: "D" },
  { name: "Desk Lamp", price: 34.99, quantity: 60, warehouse: "B" },
  { name: "USB Cable", price: 9.99, quantity: 300, warehouse: "A" },
  { name: "External HDD", price: 79.99, quantity: 45, warehouse: "C" },
  { name: "Webcam", price: 59.99, quantity: 70, warehouse: "D" },
  { name: "Headphones", price: 89.99, quantity: 55, warehouse: "B" },
  { name: "Smartphone", price: 699.99, quantity: 35, warehouse: "A" },
  { name: "Tablet", price: 329.99, quantity: 20, warehouse: "C" },
  { name: "Charger", price: 24.99, quantity: 120, warehouse: "D" },
  { name: "Backpack", price: 49.99, quantity: 65, warehouse: "B" },
  { name: "Router", price: 109.99, quantity: 30, warehouse: "A" },
  { name: "Switch", price: 89.99, quantity: 28, warehouse: "C" },
  { name: "Speakers", price: 149.99, quantity: 22, warehouse: "D" },
  { name: "Microphone", price: 79.99, quantity: 33, warehouse: "B" },
  { name: "Camera", price: 499.99, quantity: 15, warehouse: "A" },
  { name: "Tripod", price: 39.99, quantity: 50, warehouse: "C" },
  { name: "SSD", price: 119.99, quantity: 75, warehouse: "D" },
  { name: "RAM", price: 89.99, quantity: 95, warehouse: "A" },
  { name: "GPU", price: 399.99, quantity: 12, warehouse: "B" },
  { name: "CPU", price: 299.99, quantity: 18, warehouse: "C" },
  { name: "Motherboard", price: 159.99, quantity: 27, warehouse: "D" },
  { name: "Power Supply", price: 99.99, quantity: 32, warehouse: "A" },
  { name: "Case", price: 79.99, quantity: 40, warehouse: "B" },
  { name: "Cooling Fan", price: 14.99, quantity: 200, warehouse: "C" },
  { name: "Thermal Paste", price: 7.99, quantity: 180, warehouse: "D" },
  { name: "HDMI Cable", price: 12.99, quantity: 220, warehouse: "A" }
];

module.exports = products;
